---
title: "test"
output: github_document
---

# OMIP 030

```{r global-options, include=FALSE}
library(knitr)
opts_chunk$set(results='hide', warning=FALSE, message=FALSE, tidy.opts=list(width.cutoff=6000))
```

```{r libraries}
library(magrittr)
library(tidyverse)
library(fs)
library(janitor)
library(FlowRepositoryR)
library(flowCore)
library(openCyto)
library(ggcyto)
library(gplots)
library(Rtsne)

map <- purrr::map
add <- flowCore::add
filter <- dplyr::filter
```

```{r theme, include=F}
# Set common ggplot theme
flow_theme <- theme_bw() + theme(
  panel.grid.minor.x=element_blank(),
  panel.grid.minor.y=element_blank(),
  panel.grid.major.x=element_blank(),
  panel.grid.major.y=element_blank()
)
```

Load a flow workspace, which will contain all gaiting and cell expression information:

```{r load_workspace}
ws <- openWorkspace('~/analysis/data/omip/omip-030/clean/OMIP_PBMC_clean.wsp')
gs <- parseWorkspace(ws, name='TCells', 
                     path='/home/eczech/analysis/data/omip/omip-030/clean', isNcdf=FALSE)
# Extract single GatingHierarchy from GatingSet
gh <- gs[[1]]
```

```{r summarize_flow_frame, results='markup'}
print(getData(gh))
```